import datetime as dt

DATE_START = dt.datetime(2005, 1, 1)
DATE_END = dt.datetime(2021, 12, 31)

COD_ACOES = {'RRRP3': '3R PETROLEUM',
             'ALPA4': 'ALPARGATAS',
             'ABEV3': 'AMBEV S/A',
             'AMER3': 'AMERICANAS',
             'ASAI3': 'ASSAI',
             'AZUL4': 'AZUL',
             'B3SA3': 'B3',
             'BIDI11': 'BANCO INTER',
             'BPAN4': 'BANCO PAN',
             'BBSE3': 'BBSEGURIDADE',
             'BRML3': 'BR MALLS PAR',
             'BBDC3': 'BRADESCO',
             'BBDC4': 'BRADESCO',
             'BRAP4': 'BRADESPAR',
             'BBAS3': 'BRASIL',
             'BRKM5': 'BRASKEM',
             'BRFS3': 'BRF SA',
             'BPAC11': 'BTGP BANCO',
             'CRFB3': 'CARREFOUR BR',
             'CCRO3': 'CCR SA',
             'CMIG4': 'CEMIG',
             'CIEL3': 'CIELO',
             'COGN3': 'COGNA ON',
             'CPLE6': 'COPEL',
             'CSAN3': 'COSAN',
             'CPFE3': 'CPFL ENERGIA',
             'CMIN3': 'CSNMINERACAO',
             'CVCB3': 'CVC BRASIL',
             'CYRE3': 'CYRELA REALT',
             'DXCO3': 'DEXCO',
             'ECOR3': 'ECORODOVIAS',
             'ELET3': 'ELETROBRAS',
             'ELET6': 'ELETROBRAS',
             'EMBR3': 'EMBRAER',
             'ENBR3': 'ENERGIAS BR',
             'ENGI11': 'ENERGISA',
             'ENEV3': 'ENEVA',
             'EGIE3': 'ENGIE BRASIL',
             'EQTL3': 'EQUATORIAL',
             'EZTC3': 'EZTEC',
             'FLRY3': 'FLEURY',
             'GGBR4': 'GERDAU',
             'GOAU4': 'GERDAU MET',
             'GOLL4': 'GOL',
             'NTCO3': 'GRUPO NATURA',
             'SOMA3': 'GRUPO SOMA',
             'HAPV3': 'HAPVIDA',
             'HYPE3': 'HYPERA',
             'IGTI11': 'IGUATEMI S.A',
             'IRBR3': 'IRBBRASIL RE',
             'ITSA4': 'ITAUSA',
             'ITUB4': 'ITAUUNIBANCO',
             'JBSS3': 'JBS',
             'JHSF3': 'JHSF PART',
             'KLBN11': 'KLABIN S/A',
             'RENT3': 'LOCALIZA',
             'LCAM3': 'LOCAMERICA',
             'LWSA3': 'LOCAWEB',
             'LREN3': 'LOJAS RENNER',
             'MGLU3': 'MAGAZ LUIZA',
             'MRFG3': 'MARFRIG',
             'CASH3': 'MELIUZ',
             'BEEF3': 'MINERVA',
             'MRVE3': 'MRV',
             'MULT3': 'MULTIPLAN',
             'PCAR3': 'P.ACUCAR-CBD',
             'PETR3.SA': 'PETROBRAS',
             'PETR4.SA': 'PETROBRAS',
             'PRIO3': 'PETRORIO',
             'PETZ3': 'PETZ',
             'POSI3': 'POSITIVO TEC',
             'QUAL3': 'QUALICORP',
             'RADL3': 'RAIADROGASIL',
             'RDOR3': 'REDE D OR',
             'RAIL3': 'RUMO S.A.',
             'SBSP3': 'SABESP',
             'SANB11': 'SANTANDER BR',
             'CSNA3': 'SID NACIONAL',
             'SLCE3': 'SLC AGRICOLA',
             'SULA11': 'SUL AMERICA',
             'SUZB3': 'SUZANO S.A.',
             'TAEE11': 'TAESA',
             'VIVT3': 'TELEF BRASIL',
             'TIMS3': 'TIM',
             'TOTS3': 'TOTVS',
             'UGPA3': 'ULTRAPAR',
             'USIM5': 'USIMINAS',
             'VALE3': 'VALE',
             'VIIA3': 'VIA',
             'VBBR3': 'VIBRA',
             'WEGE3': 'WEG',
             'YDUQ3': 'YDUQS PART'}